/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    ConfirmDialog: typeof import('./components/ui/ConfirmDialog.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/forms/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/ui/Table.vue')['default']
  }
}
